### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jineshpatel30** [GrayGalaxy/jiosaavn-downloader#5] opened 2021-05-13 10:20 UTC
Download button gets stuck on waiting and extension shows below error. 
Playlist: https://www.jiosaavn.com/s/playlist/0f8d02afa160d2ea7d9ef4bedf677fd9/YouTube/x3VOnhuvOfLc1EngHtQQ2g__

![image](https://user-images.githubusercontent.com/35566052/118112643-e6cc1200-b402-11eb-8ef4-849c9b878af7.png)

**Comment by jineshpatel30** [comment] 2021-05-13 12:14
PS: I was able to start downloading other play list with around 400 songs but downloads pause/stuck after some time, now trying to spit it in 100 song playlist, will report back if it works

**Comment by jineshpatel30** [comment] 2021-05-13 13:15
Might be related: Extension is not able to download some single songs as well, for example [Shape of You](https://www.jiosaavn.com/song/shape-of-you/GQshUBlvAl8) gives can not download this song error

**Comment by GrayGalaxy** [comment] 2021-05-13 14:21
Thank you for your report @jineshpatel30, I will look into that. 
The problem is mainly because some songs are unavailable and some songs don't have preview urls.

**Comment by jineshpatel30** [comment] 2021-05-13 14:35
> Thank you for your report @jineshpatel30, I will look into that.
> The problem is mainly because some songs are unavailable and some songs don't have preview urls.

Is it possible to get location of playlist download before it convert to zip? (I'm assuming somewhere in temporary folder.) I was able to download 390 of 395 song from a playlist and 5 got stuck but that is resulting in No Zip creation so if it possible to extract other downloaded song it would be great.

Just FYI: Telegram Bot @JioDLBot was able to download Shape of You song and it has bit higher quality with M4A (Not much noticeable) that 320 Mp3 downloaded by this extension. Though bot doesn't support playlist download so your extension has clear edge :)

**Comment by jineshpatel30** [comment] 2021-05-13 15:07
@GrayGalaxy I was able to download those 5 stuck songs separately via this extension, so playlist download getting stuck and not creating zip has some other issue than server "Unavailable"

PS: On second attempt to download whole playlist from scratch after removing those 5 stuck song in the first attempt resulted in 2 new songs getting stuck. :(

Playlist link if you want to check yourself.
https://www.jiosaavn.com/s/playlist/0f8d02afa160d2ea7d9ef4bedf677fd9/Mixed_Queue/f,KUWsZwD9cGSw2I1RxdhQ__

![image](https://user-images.githubusercontent.com/35566052/118145114-dcbe0980-b42a-11eb-9bfd-ff370172995c.png)

**Comment by GrayGalaxy** [comment] 2021-05-13 15:34
I am actually aware of download getting stuck for long list. You can mention this to new issue.

**Comment by GrayGalaxy** [comment] 2021-05-14 18:46
I am closing this string as it is fixed in df2ff32aa591297f04c2c32e0c633c9482104706

**Closed by GrayGalaxy** 2021-05-14 18:46 UTC
Labels: bug, good first issue
